/** Industrial live-instrument visual system layered over the graph renderer. */
export const DESIGN_CSS = `
:root .sch {
  --page:#f1f2ee;--surface-1:#fafbf7;--surface-2:#e7e9e3;--ink-1:#17201d;--ink-2:#52605b;--ink-3:#7c8984;
  --border:#cdd2cb;--grid:#dde1da;--live:#17895c;--live-soft:#d9eee4;--change:#3578d4;--warn:#a96712;--danger:#c5453d;
  --header-h:66px;--context-h:46px;font-rendering:geometricPrecision;
}
:root[data-theme="dark"] .sch {
  --page:#0d1210;--surface-1:#141a17;--surface-2:#1b231f;--ink-1:#e6ece8;--ink-2:#a5b2ac;--ink-3:#718078;
  --border:#2a3530;--grid:#222b27;--live:#51d59a;--live-soft:#173a2b;--change:#70a9ff;--warn:#e3a54a;--danger:#ef7269;
}
.sch{font-family:"Avenir Next","Noto Sans SC","Segoe UI",sans-serif;letter-spacing:.005em;background:var(--page)}
.sch::before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.26;z-index:0;background-image:radial-gradient(circle at 1px 1px,color-mix(in srgb,var(--ink-3) 22%,transparent) 1px,transparent 0);background-size:22px 22px;mask-image:linear-gradient(to bottom,black,transparent 64%)}
.sch>*{position:relative;z-index:1}.sch button:focus-visible,.sch input:focus-visible,.sch select:focus-visible{outline:2px solid var(--live);outline-offset:2px}
.sch .appHeader{height:var(--header-h);min-height:var(--header-h);display:grid;grid-template-columns:auto auto minmax(130px,1fr) auto;align-items:center;gap:28px;padding:0 22px;background:color-mix(in srgb,var(--surface-1) 92%,transparent);border-bottom:1px solid var(--border);backdrop-filter:blur(18px)}
.sch .brand{display:flex;align-items:center;gap:10px;color:var(--ink-1);text-decoration:none}.sch .brand>span:last-child{display:flex;flex-direction:column}.sch .brand b{font:700 17px/1 "Avenir Next Condensed","DIN Alternate",sans-serif;letter-spacing:.04em}.sch .brand small{margin-top:4px;font:700 8px/1 ui-monospace,monospace;letter-spacing:.18em;color:var(--ink-3)}
.sch .brandMark{position:relative;width:27px;height:27px;display:block}.sch .brandMark::before,.sch .brandMark::after{content:"";position:absolute;height:1px;background:var(--ink-3);transform-origin:left center}.sch .brandMark::before{width:17px;left:5px;top:7px;transform:rotate(46deg)}.sch .brandMark::after{width:13px;left:7px;top:18px;transform:rotate(-24deg)}.sch .brandMark i{position:absolute;width:6px;height:6px;border:1.5px solid var(--live);border-radius:50%;background:var(--surface-1)}.sch .brandMark i:nth-child(1){left:1px;top:2px}.sch .brandMark i:nth-child(2){left:10px;top:14px}.sch .brandMark i:nth-child(3){right:0;bottom:2px;background:var(--live)}
.sch .spaceNav{align-self:stretch;display:flex;align-items:stretch;gap:2px}.sch .spaceNav button{position:relative;border:0;border-radius:0;padding:0 15px;background:transparent;color:var(--ink-2);font-weight:600}.sch .spaceNav button::after{content:"";position:absolute;left:15px;right:15px;bottom:-1px;height:2px;background:var(--live);transform:scaleX(0);transition:transform .18s ease}.sch .spaceNav button[aria-current="page"]{color:var(--ink-1)}.sch .spaceNav button[aria-current="page"]::after{transform:scaleX(1)}
.sch .liveReadout{min-width:0;display:flex;align-items:center;gap:8px;color:var(--ink-3);font:600 10px/1.2 ui-monospace,monospace;letter-spacing:.03em}.sch .liveBeacon{width:7px;height:7px;border-radius:50%;background:var(--live);box-shadow:0 0 0 4px color-mix(in srgb,var(--live) 13%,transparent)}
.sch .appTools{display:flex;align-items:center;gap:7px}.sch .appTools button{width:32px;height:32px;padding:0;background:transparent}.sch .searchWrap{display:flex;align-items:center;gap:5px;border:1px solid var(--border);background:var(--page);padding:0 9px;height:32px;box-sizing:border-box}.sch .searchWrap:focus-within{border-color:var(--live);box-shadow:0 0 0 2px color-mix(in srgb,var(--live) 12%,transparent)}.sch .searchWrap input[type="search"]{width:190px;border:0;padding:0;background:transparent;outline:0}.sch .appTools .sessSel{max-width:190px;height:32px;background:var(--page)}.sch .legacyControls{display:none!important}
.sch .contextBar{min-height:var(--context-h);display:flex;align-items:center;justify-content:space-between;padding:0 22px;border-bottom:1px solid var(--border);background:var(--surface-1)}.sch .systemContext,.sch .blueprintContext,.sch .activityContext{display:flex;align-items:center;gap:12px}.sch .blueprintContext,.sch .activityContext{display:none}.sch .viewSwitch{display:flex;gap:3px;padding:3px;background:var(--surface-2)}.sch .viewSwitch button{border:0;background:transparent;padding:5px 11px;font-size:11px}.sch .viewSwitch button[aria-pressed="true"]{background:var(--surface-1);box-shadow:0 1px 3px #0002}.sch .contextRule{width:1px;height:20px;background:var(--border)}.sch .contextLabel,.sch .contextBar span{color:var(--ink-3);font:600 10px/1 ui-monospace,monospace;letter-spacing:.08em;text-transform:uppercase}
.sch .driftBanner{display:none;align-items:center;gap:10px;padding:8px 22px;border-bottom:1px solid color-mix(in srgb,var(--warn) 35%,var(--border));background:color-mix(in srgb,var(--warn) 9%,var(--surface-1));font-size:11px}.sch .driftBanner.on{display:flex}.sch .driftBanner b{color:var(--warn)}.sch .driftBanner button{padding:3px 9px;background:transparent}.sch[data-space="blueprints"] .driftBanner{display:none}.sch .tableView .pickBar{display:none!important}
.sch .filters{min-height:42px;box-sizing:border-box;padding:7px 22px;background:color-mix(in srgb,var(--surface-1) 70%,transparent);flex-wrap:nowrap;overflow-x:auto;scrollbar-width:thin}.sch .filters>*{flex:0 0 auto}.sch .chip{border-radius:2px;padding:3px 8px;font-size:11px}.sch .chip .dot{border-radius:1px;width:7px;height:7px}.sch .systemWorkspace{background:transparent}.sch .stage{background:radial-gradient(circle at 50% 45%,color-mix(in srgb,var(--live) 5%,transparent),transparent 42%)}.sch .graphGrid{position:absolute;inset:0;opacity:.34;background-image:linear-gradient(var(--grid) 1px,transparent 1px),linear-gradient(90deg,var(--grid) 1px,transparent 1px);background-size:44px 44px;mask-image:radial-gradient(ellipse at center,black 20%,transparent 78%)}
.sch aside.detail{width:350px;padding:22px;background:color-mix(in srgb,var(--surface-1) 94%,transparent)}.sch aside h2{font-size:16px;letter-spacing:.01em}.sch .node rect{rx:2}.sch .node.live rect{animation:none;filter:drop-shadow(0 0 5px color-mix(in srgb,var(--live) 46%,transparent))}.sch .node.live-strong rect{fill:color-mix(in srgb,var(--live) 14%,var(--surface-1))}.sch .edge.on{stroke:var(--live);filter:drop-shadow(0 0 2px color-mix(in srgb,var(--live) 70%,transparent))}.sch footer{padding:7px 22px}.sch footer button{min-width:30px;background:transparent}
.sch .blueprintWorkspace{display:none;flex:1;min-height:0}.sch[data-space="blueprints"] .blueprintWorkspace{display:grid}.sch[data-space="blueprints"] .systemWorkspace,.sch[data-space="blueprints"] .filters,.sch[data-space="blueprints"] footer,.sch[data-space="blueprints"] .actbar{display:none!important}.sch[data-space="blueprints"] .systemContext{display:none}.sch[data-space="blueprints"] .blueprintContext{display:flex}
.sch .activityIntro{display:none;padding:24px 24px 8px}.sch .activityIntro span{color:var(--live);font:700 9px ui-monospace,monospace;letter-spacing:.15em}.sch .activityIntro h2{margin:5px 0 2px;font:700 24px/1.1 "Avenir Next Condensed",sans-serif}.sch .activityIntro p{margin:0;color:var(--ink-2)}.sch[data-space="activity"] .activityIntro{display:block}.sch[data-space="activity"] .activityContext{display:flex}.sch[data-space="activity"] .systemContext{display:none}.sch[data-space="activity"] .filters,.sch[data-space="activity"] footer{display:none!important}.sch[data-space="activity"] .systemWorkspace{flex:1 1 44%;min-height:220px}.sch[data-space="activity"] .systemWorkspace .detail{display:none}.sch[data-space="activity"] .journey{padding:10px 24px}.sch[data-space="activity"] .actbar{flex:1 1 42%;min-height:220px;border-top:1px solid var(--border);display:flex;flex-direction:column}.sch[data-space="activity"] .actList{flex:1;max-height:none;padding:8px 24px 18px}.sch[data-space="activity"] .actHead{padding:9px 24px}.sch:not([data-space="activity"]) .actbar{display:none}
.sch .tourLayer[hidden]{display:none}.sch .tourLayer{position:fixed;inset:0;z-index:40;pointer-events:none}.sch .tourSpot{position:fixed;left:0;top:0;border:2px solid var(--live);border-radius:4px;box-shadow:0 0 0 5px color-mix(in srgb,var(--live) 18%,transparent),0 0 0 9999px #07110cb5;transition:transform .24s cubic-bezier(.16,1,.3,1),width .24s cubic-bezier(.16,1,.3,1),height .24s cubic-bezier(.16,1,.3,1)}.sch .tourSpot::after{content:"";position:absolute;inset:-8px;border:1px solid color-mix(in srgb,var(--live) 50%,transparent);animation:tourPulse 1.8s ease-out infinite}.sch .tourCard{position:fixed;left:0;top:0;width:min(320px,calc(100vw - 28px));padding:20px;border:1px solid var(--border);border-top:3px solid var(--live);border-radius:3px;background:var(--surface-1);color:var(--ink-1);box-shadow:0 18px 55px #0007;pointer-events:auto;transition:transform .24s cubic-bezier(.16,1,.3,1);animation:tourEnter .24s cubic-bezier(.16,1,.3,1)}.sch .tourStep{color:var(--live);font:700 9px ui-monospace,monospace;letter-spacing:.14em}.sch .tourCard h2{margin:8px 0 7px;font:700 21px/1.1 "Avenir Next Condensed",sans-serif}.sch .tourCard p{margin:0;color:var(--ink-2);font-size:12px;line-height:1.55}.sch .tourHint{margin-top:14px;padding-top:10px;border-top:1px solid var(--border);color:var(--live);font:700 10px/1.4 ui-monospace,monospace;letter-spacing:.04em}.sch .tourSkip{margin-top:13px;padding:4px 0;border:0;background:transparent;color:var(--ink-3);font-size:10px;text-decoration:underline;text-underline-offset:3px}.sch .primaryAction{background:var(--ink-1)!important;color:var(--page)!important;border-color:var(--ink-1)!important}@keyframes tourEnter{from{opacity:0;transform:translate3d(var(--tour-x),calc(var(--tour-y) + 8px),0)}to{opacity:1;transform:translate3d(var(--tour-x),var(--tour-y),0)}}@keyframes tourPulse{0%,100%{opacity:.35;transform:scale(1)}50%{opacity:.9;transform:scale(1.02)}}
@media (max-width:980px){.sch .appHeader{grid-template-columns:auto auto 1fr;gap:12px}.sch .liveReadout{display:none}.sch .appTools .sessSel{display:none}.sch .searchWrap input[type="search"]{width:130px}.sch aside.detail{width:300px}}
@media (max-width:767px){.sch{--header-h:108px}.sch .appHeader{grid-template-columns:1fr auto;grid-template-rows:54px 54px;padding:0 13px}.sch .spaceNav{grid-row:2;grid-column:1/-1}.sch .spaceNav button{flex:1}.sch .appTools .searchWrap{display:none}.sch .brand small{display:none}.sch .contextBar{padding:0 13px}.sch .filters{overflow-x:auto;flex-wrap:nowrap;padding:7px 13px}.sch aside.detail{position:absolute;inset:0 0 0 auto;width:min(86vw,340px);z-index:8;box-sizing:border-box}.sch .editSec button,.sch .blueprintWrite{pointer-events:none;opacity:.42}.sch .tourCard{width:min(290px,calc(100vw - 20px));padding:16px}}
@media (prefers-reduced-motion:reduce){.sch *,.sch *::before,.sch *::after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
`
